Add Arbitrum Support to Defi Kit with Cow Protocol Integration
karpatkey/defi-kit pull request #215
Opened 2024-08-05 10:02 UTC by jfrancai

### What
This PR introduces Arbitrum support in the Defi Kit, starting with the integration of the Cow Protocol.

### Why
Arbitrum is a leading Layer 2 solution for DeFi, and Hopper plans to deploy its first vault on this network. 

### Implementation Details
- Updated contractAddressOverrides: Included the CowSwap order signer contract address.
- Added WETH address for arb1: Included the WETH address specific to the Arbitrum network.
- Refactored swap function: Modified the swap function to handle the Arbitrum protocol.
- Exposed arb1 in the SDK Package: Made Arbitrum network functionalities accessible through the SDK.

2024-08-07 16:51 UTC, sideris requested changes

2024-08-07 16:51 UTC, sideris commented on sdk/src/protocols/cowswap/index.ts
> +const getWethAddress = (chain: Chain) => {
please add return type

2024-08-07 16:51 UTC, sideris commented on sdk/src/protocols/cowswap/index.ts
> +const getWethAddress = (chain: Chain) => {
It should probably live somewhere else too. Not sure exactly where.

Maybe under something like `utils/getWethAddressByChain`

2024-08-07 16:51 UTC, sideris commented on sdk/src/protocols/cowswap/index.ts
> +const getWethAddress = (chain: Chain) => {
Change signature to `getWethAddressByChain`

2024-08-08 17:42 UTC, sideris commented
From structural perspective it looks great to me. 
Up to Nico or Jan to evaluate logic and approve or not. 

We also need to check Vercel issue.

2024-08-20 15:39 UTC, nledo approved these changes
Thank you for this great addition. While reviewing the PR we realised that we need to improve the natove token handling. I created a separate issue #219 for this.

2024-08-20 15:39 UTC, merged